// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("JsonProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("JsonProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing JsonProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "JsonProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "JsonProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing JsonProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
